# Generated by Django 4.2.8 on 2023-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("rating", models.FloatField(max_length=5.0)),
                ("review", models.IntegerField()),
                ("type", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="image/")),
            ],
        ),
    ]
