# Generated by Django 4.2.8 on 2024-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourBuddy", "0004_touristnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="g_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
