# Generated by Django 4.2.8 on 2024-02-14 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("TourBuddy", "0005_trip_g_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="touristnode",
            name="node",
        ),
        migrations.CreateModel(
            name="Order_Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_latitude", models.FloatField(null=True)),
                ("user_longitude", models.FloatField(null=True)),
                (
                    "item_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TourBuddy.touristnode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
