# Generated by Django 4.2.8 on 2024-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourBuddy", "0006_remove_touristnode_node_order_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_trip",
            name="user_latitude",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="order_trip",
            name="user_longitude",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
