# Generated by Django 4.2.8 on 2024-05-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbuddy', '0002_alter_trip_g_type_alter_trip_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='g_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(max_length=500),
        ),
    ]
