# Generated by Django 4.2.8 on 2023-12-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourBuddy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="location",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trip",
            name="image",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="trip",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="trip",
            name="rating",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="review",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="type",
            field=models.CharField(max_length=50),
        ),
    ]
