# Generated by Django 4.2.8 on 2024-02-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TourBuddy", "0002_trip_location_alter_trip_image_alter_trip_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="type",
            new_name="trip_type",
        ),
        migrations.AddField(
            model_name="trip",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
